import { LanguageEnum } from "../enums/language.enum";
import type { NativeLanguageNamesType } from "../types/nativeLanguagesNames.type";

export const nativeLanguageNames: NativeLanguageNamesType = {
  [LanguageEnum.AFRIKAANS]: "Afrikaans",
  [LanguageEnum.ALBANIAN]: "Shqiptare",
  [LanguageEnum.AMHARIC]: "አማርኛ",
  [LanguageEnum.ARABIC]: "عربي",
  [LanguageEnum.ARMENIAN]: "Հայերեն",
  [LanguageEnum.AZERBAIJANI]: "Azərbaycan",
  [LanguageEnum.BAMBARA]: "Bamanankan",
  [LanguageEnum.BELARUSIAN]: "беларускі",
  [LanguageEnum.BENGALI]: "বাংলা",
  [LanguageEnum.BULGARIAN]: "български",
  [LanguageEnum.CATALAN]: "Català",
  [LanguageEnum.CHINESE]: "中国人",
  [LanguageEnum.CROATIAN]: "Hrvatski",
  [LanguageEnum.CZECH]: "Čeština",
  [LanguageEnum.DANISH]: "Dansk",
  [LanguageEnum.DUTCH]: "Nederlands",
  [LanguageEnum.ENGLISH]: "English",
  [LanguageEnum.ESPERANTO]: "Esperanto",
  [LanguageEnum.FILIPINO]: "Filipino",
  [LanguageEnum.FINNISH]: "Suomalainen",
  [LanguageEnum.FRENCH]: "Français",
  [LanguageEnum.GEORGIAN]: "ქართული",
  [LanguageEnum.GERMAN]: "Deutsch",
  [LanguageEnum.GREEK]: "Ελληνικά",
  [LanguageEnum.GUJARATI]: "ગુજરાતી",
  [LanguageEnum.HAUSA]: "Hausa",
  [LanguageEnum.HEBREW]: "עִברִית",
  [LanguageEnum.HINDI]: "हिंदी",
  [LanguageEnum.HUNGARIAN]: "Magyar",
  [LanguageEnum.ICELANDIC]: "Íslenskur",
  [LanguageEnum.IGBO]: "Igbo",
  [LanguageEnum.INDONESIAN]: "Bahasa Indonesia",
  [LanguageEnum.ITALIAN]: "Italiano",
  [LanguageEnum.JAPANESE]: "日本語",
  [LanguageEnum.JAVANESE]: "Basa jawa",
  [LanguageEnum.KAZAKH]: "қазақ",
  [LanguageEnum.KHMER]: "ខ្មែរ",
  [LanguageEnum.KINYARWANDA]: "Kinyarwanda",
  [LanguageEnum.KOREAN]: "한국인",
  [LanguageEnum.KURDISH]: "Kurdî",
  [LanguageEnum.LINGALA]: "Lingala",
  [LanguageEnum.LITHUANIAN]: "Lietuvių",
  [LanguageEnum.MALAY]: "Melayu",
  [LanguageEnum.MARATHI]: "मराठी",
  [LanguageEnum.MONGOLIAN]: "Монгол",
  [LanguageEnum.NEPALI]: "नेपाली",
  [LanguageEnum.NORWEGIAN]: "Norsk",
  [LanguageEnum.OROMO]: "Afaan Oromoo",
  [LanguageEnum.PERSIAN]: "فارسی",
  [LanguageEnum.POLISH]: "Polski",
  [LanguageEnum.PORTUGUESE]: "Português",
  [LanguageEnum.PUNJABI]: "ਪੰਜਾਬੀ",
  [LanguageEnum.RUSSIAN]: "Русский",
  [LanguageEnum.SERBIAN]: "Српски",
  [LanguageEnum.SOMALI]: "Soomaali",
  [LanguageEnum.SPANISH]: "Español",
  [LanguageEnum.SUNDANESE]: "Basa Sunda",
  [LanguageEnum.SWAHILI]: "Kiswahili",
  [LanguageEnum.SWEDISH]: "Svenska",
  [LanguageEnum.TAMIL]: "தமிழ்",
  [LanguageEnum.TELEGU]: "తెలుగు",
  [LanguageEnum.THAI]: "థాయ్",
  [LanguageEnum.TURKISH]: "Türkçe",
  [LanguageEnum.TURKMEN]: "Türkmenler",
  [LanguageEnum.UKRAINIAN]: "українська",
  [LanguageEnum.URDU]: "اردو",
  [LanguageEnum.UYGHUR]: "ئۇيغۇر",
  [LanguageEnum.UZBEK]: "O'zbek",
  [LanguageEnum.VIETNAMESE]: "Tiếng Việt",
  [LanguageEnum.YORUBA]: "Yoruba",
};
